import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import { NextAuthProvider } from './Provider'

// import { FpjsProvider } from '@fingerprintjs/fingerprintjs-pro-react'

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<NextAuthProvider>
				{/* <FpjsProvider
					loadOptions={{
						apiKey: 'EXUkcnTKp7DJJ1BeYIGB',
						region: 'ap',
					}}
				> */}
				<body className={inter.className}>{children}</body>
				{/* </FpjsProvider> */}
			</NextAuthProvider>
		</html>
	)
}
